"""
Document Generator Skill - Silver Tier
Generate reports, briefings, and documents from templates.

Supports:
- CEO Briefing documents
- Meeting notes/reports
- Project status reports
- Custom document templates
- Human-in-the-loop approval
- Export to multiple formats (Markdown, PDF, TXT)
"""

import os
import sys
from pathlib import Path
from datetime import datetime
from dotenv import load_dotenv
import json

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Load environment variables
load_dotenv(PROJECT_ROOT / ".env")

# Configuration
OUTPUT_DIR = PROJECT_ROOT / "silver" / "vault" / "Generated"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


def generate_ceo_briefing(
    title: str,
    executive_summary: str,
    key_metrics: dict,
    highlights: list,
    challenges: list,
    action_items: list,
    output_format: str = 'md',
    require_approval: bool = True
) -> dict:
    """
    Generate a CEO Briefing document.
    
    Args:
        title: Briefing title
        executive_summary: High-level summary
        key_metrics: Dict of metric name -> value
        highlights: List of key highlights/wins
        challenges: List of challenges/blockers
        action_items: List of action items
        output_format: 'md', 'pdf', or 'txt' (default: 'md')
        require_approval: If True, requires human approval (default: True)
    
    Returns:
        dict: {'success': bool, 'file_path': str, 'error': str}
    """
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"CEO_Briefing_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    
    # Generate Markdown content
    content = f"""# {title}

**Generated:** {timestamp}  
**Document Type:** CEO Briefing

---

## Executive Summary

{executive_summary}

---

## Key Metrics

"""
    
    for metric, value in key_metrics.items():
        content += f"- **{metric}:** {value}\n"
    
    content += "\n---\n\n## Highlights\n\n"
    for highlight in highlights:
        content += f"✅ {highlight}\n"
    
    content += "\n---\n\n## Challenges\n\n"
    for challenge in challenges:
        content += f"⚠️ {challenge}\n"
    
    content += "\n---\n\n## Action Items\n\n"
    for i, item in enumerate(action_items, 1):
        content += f"{i}. {item}\n"
    
    content += f"\n---\n\n*This briefing was auto-generated by the Personal AI Employee system.*\n"
    
    # Prepare preview for approval
    preview_data = {
        'title': title,
        'type': 'CEO Briefing',
        'executive_summary_preview': executive_summary[:200] + ('...' if len(executive_summary) > 200 else ''),
        'metrics_count': len(key_metrics),
        'highlights_count': len(highlights),
        'challenges_count': len(challenges),
        'action_items_count': len(action_items)
    }
    
    # HUMAN-IN-THE-LOOP APPROVAL
    if require_approval:
        print("\n" + "=" * 70)
        print("DOCUMENT GENERATION - HUMAN APPROVAL REQUIRED")
        print("=" * 70)
        print(f"\n📄 DOCUMENT: {title}")
        print(f"📋 TYPE: CEO Briefing")
        print(f"⏰ GENERATED: {timestamp}")
        print(f"\n📊 CONTENT SUMMARY:")
        print(f"   - Metrics: {preview_data['metrics_count']}")
        print(f"   - Highlights: {preview_data['highlights_count']}")
        print(f"   - Challenges: {preview_data['challenges_count']}")
        print(f"   - Action Items: {preview_data['action_items_count']}")
        print(f"\n📝 EXECUTIVE SUMMARY PREVIEW:")
        print("-" * 70)
        print(preview_data['executive_summary_preview'])
        print("-" * 70)
        print(f"\nOutput format: {output_format.upper()}")
        print(f"Output directory: {OUTPUT_DIR}")
        print("\nApprove generating this document?")
        
        while True:
            response = input("Type 'yes' to approve, 'no' to cancel: ").strip().lower()
            if response in ['yes', 'y']:
                print("Document generation APPROVED\n")
                break
            elif response in ['no', 'n']:
                print("Document generation CANCELLED by user\n")
                return {
                    'success': False,
                    'error': 'User cancelled document generation',
                    'details': preview_data
                }
            else:
                print("Invalid response. Please type 'yes' or 'no'.")
    
    # Save the document
    try:
        if output_format == 'md':
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
        elif output_format == 'txt':
            file_path = OUTPUT_DIR / f"{filename}.txt"
            # Convert markdown to plain text
            plain_text = content.replace('#', '').replace('*', '').replace('---', '')
            file_path.write_text(plain_text, encoding='utf-8')
        elif output_format == 'pdf':
            # For PDF, save as markdown and note conversion needed
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
            print("[Note] PDF conversion requires additional dependencies (e.g., pandoc, wkhtmltopdf)")
            print("[Note] Document saved as Markdown. Convert manually if PDF needed.")
        else:
            return {'success': False, 'error': f'Unsupported format: {output_format}'}
        
        print(f"✅ Document generated successfully!")
        print(f"📁 Saved to: {file_path}")
        
        return {
            'success': True,
            'file_path': str(file_path),
            'filename': file_path.name,
            'format': output_format,
            'details': preview_data
        }
        
    except Exception as e:
        error_msg = f"Failed to generate document: {type(e).__name__}: {str(e)}"
        print(f"❌ {error_msg}")
        return {
            'success': False,
            'error': error_msg,
            'details': preview_data
        }


def generate_meeting_report(
    meeting_title: str,
    date: str,
    attendees: list,
    agenda: list,
    discussion_notes: str,
    decisions: list,
    action_items: list,
    output_format: str = 'md',
    require_approval: bool = True
) -> dict:
    """
    Generate a meeting report/notes document.
    
    Args:
        meeting_title: Title of the meeting
        date: Meeting date
        attendees: List of attendee names
        agenda: List of agenda items
        discussion_notes: Main discussion notes
        decisions: List of decisions made
        action_items: List of action items with owners
        output_format: 'md', 'pdf', or 'txt' (default: 'md')
        require_approval: If True, requires human approval (default: True)
    
    Returns:
        dict: {'success': bool, 'file_path': str, 'error': str}
    """
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"Meeting_Notes_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    
    # Generate Markdown content
    content = f"""# {meeting_title}

**Date:** {date}  
**Generated:** {timestamp}  
**Document Type:** Meeting Report

---

## Attendees

"""
    
    for attendee in attendees:
        content += f"- {attendee}\n"
    
    content += "\n---\n\n## Agenda\n\n"
    for i, item in enumerate(agenda, 1):
        content += f"{i}. {item}\n"
    
    content += "\n---\n\n## Discussion Notes\n\n"
    content += discussion_notes + "\n"
    
    content += "\n---\n\n## Decisions Made\n\n"
    for decision in decisions:
        content += f"✅ {decision}\n"
    
    content += "\n---\n\n## Action Items\n\n"
    for i, item in enumerate(action_items, 1):
        content += f"{i}. {item}\n"
    
    content += f"\n---\n\n*Meeting notes auto-generated by the Personal AI Employee system.*\n"
    
    # Prepare preview for approval
    preview_data = {
        'title': meeting_title,
        'type': 'Meeting Report',
        'date': date,
        'attendees_count': len(attendees),
        'agenda_items': len(agenda),
        'decisions_count': len(decisions),
        'action_items_count': len(action_items)
    }
    
    # HUMAN-IN-THE-LOOP APPROVAL
    if require_approval:
        print("\n" + "=" * 70)
        print("DOCUMENT GENERATION - HUMAN APPROVAL REQUIRED")
        print("=" * 70)
        print(f"\n📄 DOCUMENT: {meeting_title}")
        print(f"📋 TYPE: Meeting Report")
        print(f"📅 DATE: {date}")
        print(f"⏰ GENERATED: {timestamp}")
        print(f"\n📊 CONTENT SUMMARY:")
        print(f"   - Attendees: {preview_data['attendees_count']}")
        print(f"   - Agenda Items: {preview_data['agenda_items']}")
        print(f"   - Decisions: {preview_data['decisions_count']}")
        print(f"   - Action Items: {preview_data['action_items_count']}")
        print(f"\n📝 DISCUSSION PREVIEW:")
        print("-" * 70)
        print(discussion_notes[:300] + ('...\n[Truncated]' if len(discussion_notes) > 300 else ''))
        print("-" * 70)
        print(f"\nOutput format: {output_format.upper()}")
        print(f"Output directory: {OUTPUT_DIR}")
        print("\nApprove generating this document?")
        
        while True:
            response = input("Type 'yes' to approve, 'no' to cancel: ").strip().lower()
            if response in ['yes', 'y']:
                print("Document generation APPROVED\n")
                break
            elif response in ['no', 'n']:
                print("Document generation CANCELLED by user\n")
                return {
                    'success': False,
                    'error': 'User cancelled document generation',
                    'details': preview_data
                }
            else:
                print("Invalid response. Please type 'yes' or 'no'.")
    
    # Save the document
    try:
        if output_format == 'md':
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
        elif output_format == 'txt':
            file_path = OUTPUT_DIR / f"{filename}.txt"
            plain_text = content.replace('#', '').replace('*', '').replace('---', '')
            file_path.write_text(plain_text, encoding='utf-8')
        elif output_format == 'pdf':
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
            print("[Note] PDF conversion requires additional dependencies")
        else:
            return {'success': False, 'error': f'Unsupported format: {output_format}'}
        
        print(f"✅ Document generated successfully!")
        print(f"📁 Saved to: {file_path}")
        
        return {
            'success': True,
            'file_path': str(file_path),
            'filename': file_path.name,
            'format': output_format,
            'details': preview_data
        }
        
    except Exception as e:
        error_msg = f"Failed to generate document: {type(e).__name__}: {str(e)}"
        print(f"❌ {error_msg}")
        return {
            'success': False,
            'error': error_msg,
            'details': preview_data
        }


def generate_status_report(
    project_name: str,
    reporting_period: str,
    status: str,
    completed_this_period: list,
    planned_next_period: list,
    risks: list,
    budget_status: str = "",
    timeline_status: str = "",
    output_format: str = 'md',
    require_approval: bool = True
) -> dict:
    """
    Generate a project status report.
    
    Args:
        project_name: Name of the project
        reporting_period: Period covered (e.g., "Week 12, March 2026")
        status: Overall status (Green/Yellow/Red)
        completed_this_period: List of completed items
        planned_next_period: List of planned items
        risks: List of risks/concerns
        budget_status: Budget status summary
        timeline_status: Timeline status summary
        output_format: 'md', 'pdf', or 'txt' (default: 'md')
        require_approval: If True, requires human approval (default: True)
    
    Returns:
        dict: {'success': bool, 'file_path': str, 'error': str}
    """
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"Status_Report_{project_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d')}"
    
    # Status emoji
    status_emoji = {'Green': '🟢', 'Yellow': '🟡', 'Red': '🔴'}.get(status, '⚪')
    
    # Generate Markdown content
    content = f"""# {project_name} - Status Report

**Reporting Period:** {reporting_period}  
**Generated:** {timestamp}  
**Document Type:** Project Status Report

---

## Overall Status

{status_emoji} **{status}**

"""
    
    if budget_status:
        content += f"\n### Budget\n{budget_status}\n"
    
    if timeline_status:
        content += f"\n### Timeline\n{timeline_status}\n"
    
    content += "\n---\n\n## Completed This Period\n\n"
    for item in completed_this_period:
        content += f"✅ {item}\n"
    
    content += "\n---\n\n## Planned for Next Period\n\n"
    for item in planned_next_period:
        content += f"📋 {item}\n"
    
    content += "\n---\n\n## Risks & Concerns\n\n"
    if risks:
        for risk in risks:
            content += f"⚠️ {risk}\n"
    else:
        content += "*No significant risks identified.*\n"
    
    content += f"\n---\n\n*Status report auto-generated by the Personal AI Employee system.*\n"
    
    # Prepare preview for approval
    preview_data = {
        'project': project_name,
        'type': 'Status Report',
        'period': reporting_period,
        'status': status,
        'completed_count': len(completed_this_period),
        'planned_count': len(planned_next_period),
        'risks_count': len(risks)
    }
    
    # HUMAN-IN-THE-LOOP APPROVAL
    if require_approval:
        print("\n" + "=" * 70)
        print("DOCUMENT GENERATION - HUMAN APPROVAL REQUIRED")
        print("=" * 70)
        print(f"\n📄 DOCUMENT: {project_name} Status Report")
        print(f"📋 TYPE: Project Status Report")
        print(f"📅 PERIOD: {reporting_period}")
        print(f"⏰ GENERATED: {timestamp}")
        print(f"\n📊 CONTENT SUMMARY:")
        print(f"   - Status: {status_emoji} {status}")
        print(f"   - Completed: {preview_data['completed_count']}")
        print(f"   - Planned: {preview_data['planned_count']}")
        print(f"   - Risks: {preview_data['risks_count']}")
        print(f"\nOutput format: {output_format.upper()}")
        print(f"Output directory: {OUTPUT_DIR}")
        print("\nApprove generating this document?")
        
        while True:
            response = input("Type 'yes' to approve, 'no' to cancel: ").strip().lower()
            if response in ['yes', 'y']:
                print("Document generation APPROVED\n")
                break
            elif response in ['no', 'n']:
                print("Document generation CANCELLED by user\n")
                return {
                    'success': False,
                    'error': 'User cancelled document generation',
                    'details': preview_data
                }
            else:
                print("Invalid response. Please type 'yes' or 'no'.")
    
    # Save the document
    try:
        if output_format == 'md':
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
        elif output_format == 'txt':
            file_path = OUTPUT_DIR / f"{filename}.txt"
            plain_text = content.replace('#', '').replace('*', '').replace('---', '')
            file_path.write_text(plain_text, encoding='utf-8')
        elif output_format == 'pdf':
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
            print("[Note] PDF conversion requires additional dependencies")
        else:
            return {'success': False, 'error': f'Unsupported format: {output_format}'}
        
        print(f"✅ Document generated successfully!")
        print(f"📁 Saved to: {file_path}")
        
        return {
            'success': True,
            'file_path': str(file_path),
            'filename': file_path.name,
            'format': output_format,
            'details': preview_data
        }
        
    except Exception as e:
        error_msg = f"Failed to generate document: {type(e).__name__}: {str(e)}"
        print(f"❌ {error_msg}")
        return {
            'success': False,
            'error': error_msg,
            'details': preview_data
        }


def generate_custom_document(
    title: str,
    template: str,
    content_data: dict,
    output_format: str = 'md',
    require_approval: bool = True
) -> dict:
    """
    Generate a custom document from a template string.
    
    Args:
        title: Document title
        template: Template string with {placeholders}
        content_data: Dict of placeholder -> value
        output_format: 'md', 'pdf', or 'txt' (default: 'md')
        require_approval: If True, requires human approval (default: True)
    
    Returns:
        dict: {'success': bool, 'file_path': str, 'error': str}
    """
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    filename = f"{title.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
    
    # Add title and timestamp to content
    full_content = f"# {title}\n\n**Generated:** {timestamp}\n\n{template}"
    
    # Substitute placeholders
    try:
        content = full_content.format(**content_data)
    except KeyError as e:
        return {'success': False, 'error': f'Missing placeholder: {e}'}
    
    # Prepare preview
    preview_data = {
        'title': title,
        'type': 'Custom Document',
        'placeholders_filled': len(content_data),
        'content_preview': content[:300] + ('...\n[Truncated]' if len(content) > 300 else '')
    }
    
    # HUMAN-IN-THE-LOOP APPROVAL
    if require_approval:
        print("\n" + "=" * 70)
        print("DOCUMENT GENERATION - HUMAN APPROVAL REQUIRED")
        print("=" * 70)
        print(f"\n📄 DOCUMENT: {title}")
        print(f"📋 TYPE: Custom Document")
        print(f"⏰ GENERATED: {timestamp}")
        print(f"\n📊 PLACEHOLDERS FILLED: {len(content_data)}")
        print(f"\n📝 CONTENT PREVIEW:")
        print("-" * 70)
        print(preview_data['content_preview'])
        print("-" * 70)
        print(f"\nOutput format: {output_format.upper()}")
        print(f"Output directory: {OUTPUT_DIR}")
        print("\nApprove generating this document?")
        
        while True:
            response = input("Type 'yes' to approve, 'no' to cancel: ").strip().lower()
            if response in ['yes', 'y']:
                print("Document generation APPROVED\n")
                break
            elif response in ['no', 'n']:
                print("Document generation CANCELLED by user\n")
                return {
                    'success': False,
                    'error': 'User cancelled document generation',
                    'details': preview_data
                }
            else:
                print("Invalid response. Please type 'yes' or 'no'.")
    
    # Save the document
    try:
        if output_format == 'md':
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
        elif output_format == 'txt':
            file_path = OUTPUT_DIR / f"{filename}.txt"
            plain_text = content.replace('#', '').replace('*', '').replace('---', '')
            file_path.write_text(plain_text, encoding='utf-8')
        elif output_format == 'pdf':
            file_path = OUTPUT_DIR / f"{filename}.md"
            file_path.write_text(content, encoding='utf-8')
            print("[Note] PDF conversion requires additional dependencies")
        else:
            return {'success': False, 'error': f'Unsupported format: {output_format}'}
        
        print(f"✅ Document generated successfully!")
        print(f"📁 Saved to: {file_path}")
        
        return {
            'success': True,
            'file_path': str(file_path),
            'filename': file_path.name,
            'format': output_format,
            'details': preview_data
        }
        
    except Exception as e:
        error_msg = f"Failed to generate document: {type(e).__name__}: {str(e)}"
        print(f"❌ {error_msg}")
        return {
            'success': False,
            'error': error_msg,
            'details': preview_data
        }


# CLI Interface
if __name__ == "__main__":
    print("=" * 70)
    print("DOCUMENT GENERATOR SKILL - Silver Tier")
    print("=" * 70)
    print("\nUsage examples:")
    print("  python document_generator.py --ceo-briefing")
    print("  python document_generator.py --meeting-report")
    print("  python document_generator.py --status-report")
    print("  python document_generator.py --custom")
    print("\n" + "=" * 70)
    
    import argparse
    
    parser = argparse.ArgumentParser(description='Document Generator Skill')
    parser.add_argument('--ceo-briefing', action='store_true', help='Generate CEO Briefing')
    parser.add_argument('--meeting-report', action='store_true', help='Generate Meeting Report')
    parser.add_argument('--status-report', action='store_true', help='Generate Status Report')
    parser.add_argument('--custom', action='store_true', help='Generate Custom Document')
    parser.add_argument('--format', type=str, default='md', choices=['md', 'txt', 'pdf'], help='Output format')
    parser.add_argument('--no-approval', action='store_true', help='Skip approval prompt')
    
    args = parser.parse_args()
    
    if args.ceo_briefing:
        print("\n[CEO Briefing Generator]")
        title = input("Briefing Title: ").strip()
        summary = input("Executive Summary: ").strip()
        
        print("\nEnter key metrics (format: name:value, one per line, empty line to finish):")
        metrics = {}
        while True:
            line = input().strip()
            if not line:
                break
            if ':' in line:
                name, value = line.split(':', 1)
                metrics[name.strip()] = value.strip()
        
        print("\nEnter highlights (one per line, empty line to finish):")
        highlights = []
        while True:
            line = input().strip()
            if not line:
                break
            highlights.append(line)
        
        print("\nEnter challenges (one per line, empty line to finish):")
        challenges = []
        while True:
            line = input().strip()
            if not line:
                break
            challenges.append(line)
        
        print("\nEnter action items (one per line, empty line to finish):")
        action_items = []
        while True:
            line = input().strip()
            if not line:
                break
            action_items.append(line)
        
        result = generate_ceo_briefing(
            title=title,
            executive_summary=summary,
            key_metrics=metrics,
            highlights=highlights,
            challenges=challenges,
            action_items=action_items,
            output_format=args.format,
            require_approval=not args.no_approval
        )
    
    elif args.meeting_report:
        print("\n[Meeting Report Generator]")
        meeting_title = input("Meeting Title: ").strip()
        date = input("Meeting Date: ").strip()
        
        print("\nEnter attendees (one per line, empty line to finish):")
        attendees = []
        while True:
            line = input().strip()
            if not line:
                break
            attendees.append(line)
        
        print("\nEnter agenda items (one per line, empty line to finish):")
        agenda = []
        while True:
            line = input().strip()
            if not line:
                break
            agenda.append(line)
        
        discussion_notes = input("\nDiscussion Notes: ").strip()
        
        print("\nEnter decisions (one per line, empty line to finish):")
        decisions = []
        while True:
            line = input().strip()
            if not line:
                break
            decisions.append(line)
        
        print("\nEnter action items (one per line, empty line to finish):")
        action_items = []
        while True:
            line = input().strip()
            if not line:
                break
            action_items.append(line)
        
        result = generate_meeting_report(
            meeting_title=meeting_title,
            date=date,
            attendees=attendees,
            agenda=agenda,
            discussion_notes=discussion_notes,
            decisions=decisions,
            action_items=action_items,
            output_format=args.format,
            require_approval=not args.no_approval
        )
    
    elif args.status_report:
        print("\n[Status Report Generator]")
        project_name = input("Project Name: ").strip()
        reporting_period = input("Reporting Period: ").strip()
        status = input("Overall Status (Green/Yellow/Red): ").strip()
        
        print("\nEnter completed items (one per line, empty line to finish):")
        completed = []
        while True:
            line = input().strip()
            if not line:
                break
            completed.append(line)
        
        print("\nEnter planned items (one per line, empty line to finish):")
        planned = []
        while True:
            line = input().strip()
            if not line:
                break
            planned.append(line)
        
        print("\nEnter risks (one per line, empty line to finish):")
        risks = []
        while True:
            line = input().strip()
            if not line:
                break
            risks.append(line)
        
        budget_status = input("\nBudget Status (optional): ").strip()
        timeline_status = input("Timeline Status (optional): ").strip()
        
        result = generate_status_report(
            project_name=project_name,
            reporting_period=reporting_period,
            status=status,
            completed_this_period=completed,
            planned_next_period=planned,
            risks=risks,
            budget_status=budget_status,
            timeline_status=timeline_status,
            output_format=args.format,
            require_approval=not args.no_approval
        )
    
    elif args.custom:
        print("\n[Custom Document Generator]")
        title = input("Document Title: ").strip()
        
        print("\nEnter template (use {placeholders}, end with empty line):")
        template_lines = []
        while True:
            line = input().strip()
            if not line:
                break
            template_lines.append(line)
        template = '\n'.join(template_lines)
        
        print("\nEnter placeholder values (format: placeholder:value, empty line to finish):")
        content_data = {}
        while True:
            line = input().strip()
            if not line:
                break
            if ':' in line:
                key, value = line.split(':', 1)
                content_data[key.strip()] = value.strip()
        
        result = generate_custom_document(
            title=title,
            template=template,
            content_data=content_data,
            output_format=args.format,
            require_approval=not args.no_approval
        )
    
    else:
        parser.print_help()
        sys.exit(1)
    
    if result['success']:
        print(f"\n✅ {result.get('message', 'Document generated successfully!')}")
        print(f"📁 File: {result['file_path']}")
    else:
        print(f"\n❌ {result.get('error', 'Unknown error')}")
