'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { getPlans } from '@/lib/api-client';
import { Plan } from '@/types';

export default function PlansPage() {
  const [plans, setPlans] = useState<Plan[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedPlan, setSelectedPlan] = useState<Plan | null>(null);

  // Load plans
  const loadPlans = async () => {
    try {
      const data = await getPlans(50);
      setPlans(data.plans);
    } catch (error) {
      console.error('Error loading plans:', error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadPlans();
  }, []);

  // Format date
  const formatDate = (dateString: string) => {
    if (!dateString) return 'Unknown';
    const date = new Date(dateString);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    });
  };

  // View plan details
  const viewPlan = (plan: Plan) => {
    setSelectedPlan(plan);
  };

  // Close modal
  const closeModal = () => {
    setSelectedPlan(null);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-2 border-purple-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading plans...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div>
              <div className="flex items-center gap-2 text-sm text-gray-500 mb-1">
                <Link href="/" className="hover:text-blue-600">
                  🏠 Dashboard
                </Link>
                <span>/</span>
                <span className="text-gray-900 font-medium">📋 Plans</span>
              </div>
              <h1 className="text-2xl font-bold text-gray-900">
                📋 AI Generated Plans
              </h1>
              <p className="text-sm text-gray-500 mt-1">
                Strategic plans created by your Personal AI Employee
              </p>
            </div>
            <Link
              href="/"
              className="px-4 py-2 bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 transition-colors"
            >
              ← Back to Dashboard
            </Link>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Stats */}
        <div className="bg-white rounded-lg border border-gray-200 p-6 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <p className="text-sm text-gray-500">Total Plans</p>
              <p className="text-3xl font-bold text-purple-600">{plans.length}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">This Week</p>
              <p className="text-3xl font-bold text-blue-600">
                {plans.filter(p => {
                  const planDate = new Date(p.created_at);
                  const weekAgo = new Date();
                  weekAgo.setDate(weekAgo.getDate() - 7);
                  return planDate > weekAgo;
                }).length}
              </p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Latest</p>
              <p className="text-lg font-semibold text-gray-900 truncate">
                {plans.length > 0 ? plans[0].title : 'N/A'}
              </p>
            </div>
          </div>
        </div>

        {/* Plans List */}
        <div className="bg-white rounded-lg border border-gray-200">
          <div className="p-6 border-b border-gray-200">
            <h2 className="text-lg font-semibold text-gray-900">
              📄 All Plans
            </h2>
          </div>

          {plans.length === 0 ? (
            <div className="text-center py-12 text-gray-500">
              <p className="text-lg">📭 No plans yet</p>
              <p className="text-sm mt-1">Plans will appear here when generated by the AI reasoning engine.</p>
            </div>
          ) : (
            <div className="divide-y divide-gray-200">
              {plans.map((plan) => (
                <div
                  key={plan.id}
                  className="p-6 hover:bg-gray-50 transition-colors cursor-pointer"
                  onClick={() => viewPlan(plan)}
                >
                  <div className="flex items-start justify-between">
                    <div className="flex-1">
                      <h3 className="text-lg font-semibold text-gray-900 mb-2">
                        {plan.title}
                      </h3>
                      {plan.summary && (
                        <p className="text-sm text-gray-600 mb-3 line-clamp-2">
                          {plan.summary}
                        </p>
                      )}
                      <div className="flex items-center gap-4 text-xs text-gray-500">
                        <span>📅 {formatDate(plan.created_at)}</span>
                        <span>📁 {plan.source_file}</span>
                      </div>
                    </div>
                    <div className="ml-4">
                      <button
                        className="px-4 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 transition-colors text-sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          viewPlan(plan);
                        }}
                      >
                        View Details
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>

      {/* Plan Details Modal */}
      {selectedPlan && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-4xl w-full max-h-[80vh] overflow-hidden">
            <div className="p-6 border-b border-gray-200 flex items-center justify-between">
              <h2 className="text-xl font-bold text-gray-900">
                {selectedPlan.title}
              </h2>
              <button
                onClick={closeModal}
                className="text-gray-400 hover:text-gray-600 text-2xl"
              >
                ×
              </button>
            </div>

            <div className="p-6 overflow-y-auto max-h-[60vh]">
              <div className="mb-4">
                <h3 className="text-sm font-semibold text-gray-700 mb-2">
                  📅 Created
                </h3>
                <p className="text-sm text-gray-600">
                  {formatDate(selectedPlan.created_at)}
                </p>
              </div>

              {selectedPlan.summary && (
                <div className="mb-6">
                  <h3 className="text-sm font-semibold text-gray-700 mb-2">
                    📝 Summary
                  </h3>
                  <p className="text-sm text-gray-600 whitespace-pre-wrap">
                    {selectedPlan.summary}
                  </p>
                </div>
              )}

              {selectedPlan.next_step && (
                <div className="mb-6">
                  <h3 className="text-sm font-semibold text-gray-700 mb-2">
                    🎯 Suggested Next Step
                  </h3>
                  <p className="text-sm text-gray-600 whitespace-pre-wrap">
                    {selectedPlan.next_step}
                  </p>
                </div>
              )}

              {selectedPlan.content && (
                <div className="mb-6">
                  <h3 className="text-sm font-semibold text-gray-700 mb-2">
                    📄 Full Content
                  </h3>
                  <div className="bg-gray-50 rounded-lg p-4">
                    <pre className="text-sm text-gray-800 whitespace-pre-wrap font-sans">
                      {selectedPlan.content}
                    </pre>
                  </div>
                </div>
              )}

              <div className="mb-4">
                <h3 className="text-sm font-semibold text-gray-700 mb-2">
                  📁 Source File
                </h3>
                <p className="text-sm text-gray-600 font-mono">
                  {selectedPlan.source_file}
                </p>
              </div>
            </div>

            <div className="p-6 border-t border-gray-200 flex justify-end gap-3">
              <button
                onClick={closeModal}
                className="px-4 py-2 bg-gray-100 text-gray-700 rounded-md hover:bg-gray-200 transition-colors"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Footer */}
      <footer className="bg-white border-t border-gray-200 mt-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <p className="text-center text-sm text-gray-500">
            Silver Tier Personal AI Employee Dashboard © 2026
          </p>
        </div>
      </footer>
    </div>
  );
}
