"""
Silver Tier - Plan Executor
Automatically executes plans generated by reasoning engine.
Handles:
- Email sending (with approval)
- LinkedIn posting (auto if triggered by email)
- File operations (with approval for sensitive actions)
- MCP server integration
"""

import os
import sys
import time
import json
import re
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

# Fix Windows console encoding
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

# Load environment variables
load_dotenv()

# Configuration
VAULT_PATH = Path("silver/vault")
PLANS_PATH = VAULT_PATH / "Plans"
NEEDS_ACTION_PATH = VAULT_PATH / "Needs_Action"
INBOX_PATH = VAULT_PATH / "Inbox"
EXECUTOR_LOG = Path("silver/executor.log")

# Track executed plans
EXECUTED_PLANS_FILE = VAULT_PATH / "memory" / "executed_plans.json"

# Logging setup
def log(message, level="INFO"):
    """Log message to file and console"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_line = f"{timestamp} | {level:8s} | {message}"
    print(log_line)
    try:
        with open(EXECUTOR_LOG, "a", encoding="utf-8") as f:
            f.write(log_line + "\n")
    except Exception as e:
        print(f"Error writing to log: {e}")

# Load executed plans memory
def load_executed_plans():
    """Load list of already executed plans"""
    if EXECUTED_PLANS_FILE.exists():
        with open(EXECUTED_PLANS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return []

# Save executed plan
def save_executed_plan(plan_file):
    """Mark a plan as executed"""
    executed = load_executed_plans()
    executed.append(plan_file.name)
    EXECUTED_PLANS_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(EXECUTED_PLANS_FILE, "w", encoding="utf-8") as f:
        json.dump(executed, f, indent=2)

# Check if plan already executed
def is_plan_executed(plan_file):
    """Check if plan was already executed"""
    # DISABLED: Always process plans to allow approval prompts
    # This ensures approval prompts are shown even for previously processed plans
    return False

# Import email skill
def send_email_with_approval(recipient, subject, body):
    """Send email with human approval"""
    log(f"Email send requested: {recipient} - {subject}")
    
    try:
        sys.path.insert(0, str(Path("silver/skills/email-send").resolve()))
        from email_send import send_email
        
        result = send_email(recipient, subject, body, require_approval=True)
        
        if result['success']:
            log(f"Email sent successfully to {recipient}")
            return True
        else:
            log(f"Email send failed: {result.get('error', 'Unknown error')}", "ERROR")
            return False
            
    except Exception as e:
        log(f"Error sending email: {type(e).__name__}: {str(e)}", "ERROR")
        return False

# Import LinkedIn skill
def post_to_linkedin_auto(content, post_title="Business Update"):
    """Post to LinkedIn (auto-triggered)"""
    log(f"LinkedIn post requested: {post_title}")
    
    try:
        sys.path.insert(0, str(Path("silver/skills/linkedin-post").resolve()))
        from linkedin_post import post_to_linkedin
        
        result = post_to_linkedin(content, post_title)
        
        if result['success']:
            log(f"LinkedIn post successful: {post_title}")
            return True
        else:
            log(f"LinkedIn post failed: {result.get('error', 'Unknown error')}", "ERROR")
            return False
            
    except Exception as e:
        log(f"Error posting to LinkedIn: {type(e).__name__}: {str(e)}", "ERROR")
        return False

# Check approval for sensitive actions
def check_approval_for_action(action_type, action_data):
    """Check if action needs approval and wait for it"""
    try:
        sys.path.insert(0, str(Path("silver/skills/human-approval").resolve()))
        from human_approval import check_approval_needed
        
        return check_approval_needed(action_type, action_data)
    except Exception as e:
        log(f"Error checking approval: {e}", "ERROR")
        return False  # Default to not proceeding on error

# Parse plan file
def parse_plan(plan_file):
    """Parse plan markdown file and extract tasks"""
    with open(plan_file, "r", encoding="utf-8") as f:
        content = f.read()
    
    tasks = []
    current_task = {}
    
    lines = content.split("\n")
    for line in lines:
        # Detect task headers
        if line.startswith("### Task"):
            if current_task:
                tasks.append(current_task)
            current_task = {"raw": line}
        elif line.startswith("- **Source File**:"):
            current_task["source_file"] = line.replace("- **Source File**:", "").strip()
        elif line.startswith("- **Summary**:"):
            current_task["summary"] = line.replace("- **Summary**:", "").strip()
        elif line.startswith("- **Suggested Next Step**:"):
            current_task["next_step"] = line.replace("- **Suggested Next Step**:", "").strip()
        elif line.startswith("1. "):
            # Action step
            if "action_steps" not in current_task:
                current_task["action_steps"] = []
            current_task["action_steps"].append(line[3:].strip())
    
    if current_task:
        tasks.append(current_task)
    
    return tasks

# Determine action type from task
def determine_action_type(task):
    """Determine what action to take based on task content"""
    summary = task.get("summary", "").lower()
    next_step = task.get("next_step", "").lower()
    action_steps = " ".join(task.get("action_steps", [])).lower()
    
    # Check for email-related tasks
    if any(word in summary or word in next_step or word in action_steps 
           for word in ["email", "send", "reply", "respond", "contact"]):
        return "email"
    
    # Check for LinkedIn-related tasks
    if any(word in summary or word in next_step or word in action_steps 
           for word in ["linkedin", "post", "social media", "update"]):
        return "linkedin"
    
    # Check for file operations
    if any(word in summary or word in next_step or word in action_steps 
           for word in ["delete", "move", "copy", "file", "document"]):
        return "file_operation"
    
    # Check for review tasks (no action needed, just informational)
    if any(word in summary or word in next_step or word in action_steps 
           for word in ["review", "read", "understand", "analyze"]):
        return "review"
    
    return "general"

# Execute task
def execute_task(task, plan_file):
    """Execute a single task from the plan"""
    action_type = determine_action_type(task)
    log(f"Executing task: {task.get('summary', 'Unknown')[:50]}...")
    log(f"Action type: {action_type}")
    
    if action_type == "email":
        # Extract email details from source file
        source_file = task.get("source_file", "")
        if source_file:
            # Try to find the original email file
            email_file = INBOX_PATH / source_file.replace("TODO_", "email_")
            if not email_file.exists():
                # Search in Needs_Action
                email_file = NEEDS_ACTION_PATH / source_file
            
            if email_file.exists():
                with open(email_file, "r", encoding="utf-8") as f:
                    email_content = f.read()
                
                # Extract email details
                recipient = "Unknown"  # Would need to parse from email
                subject = f"Re: {task.get('summary', '')}"
                body = f"Regarding: {task.get('next_step', '')}"
                
                # Ask for approval and send
                log("Requesting approval for email send...")
                if send_email_with_approval(recipient, subject, body):
                    log("Task completed: Email sent")
                    return True
            else:
                log(f"Source email file not found: {email_file}", "WARNING")
        
        log("Email task requires manual intervention", "WARNING")
        return False
        
    elif action_type == "linkedin":
        # Auto-post to LinkedIn
        content = task.get("next_step", "")
        if post_to_linkedin_auto(content):
            log("Task completed: LinkedIn posted")
            return True
        return False
        
    elif action_type == "file_operation":
        # Check approval for sensitive file operations
        log("File operation detected - checking approval...")
        if check_approval_for_action("file_operation", task):
            log("Approval granted for file operation")
            # Execute file operation here
            return True
        else:
            log("File operation cancelled or pending approval", "WARNING")
            return False
            
    elif action_type == "review":
        # Review tasks are informational - mark as complete
        log("Review task - no action required")
        return True
        
    else:
        # General task - log and mark for manual review
        log(f"General task requires manual review: {task.get('summary', '')}", "INFO")
        return True

# Execute plan
def execute_plan(plan_file):
    """Execute all tasks in a plan"""
    log(f"Executing plan: {plan_file.name}")
    
    tasks = parse_plan(plan_file)
    log(f"Found {len(tasks)} task(s) in plan")
    
    completed = 0
    failed = 0
    
    for task in tasks:
        try:
            if execute_task(task, plan_file):
                completed += 1
            else:
                failed += 1
        except Exception as e:
            log(f"Error executing task: {type(e).__name__}: {str(e)}", "ERROR")
            failed += 1
    
    log(f"Plan execution complete: {completed} succeeded, {failed} failed")
    
    # Mark plan as executed
    save_executed_plan(plan_file)
    
    return completed, failed

# Main executor loop
def main():
    """Main executor loop - checks for new plans every 30 seconds"""
    log("=" * 70)
    log("SILVER TIER PLAN EXECUTOR STARTING")
    log("=" * 70)
    
    # Ensure directories exist
    PLANS_PATH.mkdir(parents=True, exist_ok=True)
    EXECUTED_PLANS_FILE.parent.mkdir(parents=True, exist_ok=True)
    
    log(f"Watching Plans folder: {PLANS_PATH}")
    log("Checking every 30 seconds")
    log("=" * 70)
    
    while True:
        try:
            # Get all plan files
            plan_files = sorted(PLANS_PATH.glob("Plan_*.md"))
            
            log(f"Found {len(plan_files)} plan file(s)")
            
            # Execute new plans
            for plan_file in plan_files:
                if not is_plan_executed(plan_file):
                    log(f"New plan detected: {plan_file.name}")
                    execute_plan(plan_file)
                else:
                    log(f"Skipping already executed: {plan_file.name}")
            
            # Wait before next check
            time.sleep(30)
            
        except KeyboardInterrupt:
            log("Executor stopped by user")
            break
        except Exception as e:
            log(f"Error in executor loop: {type(e).__name__}: {str(e)}", "ERROR")
            time.sleep(30)

if __name__ == "__main__":
    main()
